"""retirando unique True de section

Revision ID: 3941bee7a5a0
Revises: 7b31f2903e61
Create Date: 2025-05-23 20:47:47.912525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3941bee7a5a0'
down_revision: Union[str, None] = '7b31f2903e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_section_key'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('products_section_key'), 'products', ['section'])
    # ### end Alembic commands ###
