"""ajuste nos campos de Product

Revision ID: 7fd3158d933a
Revises: a29912690bbf
Create Date: 2025-05-23 15:04:40.181608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fd3158d933a'
down_revision: Union[str, None] = 'a29912690bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('bar_code', sa.VARCHAR(length=100), nullable=False))
    op.add_column('products', sa.Column('section', sa.VARCHAR(length=100), nullable=False))
    op.add_column('products', sa.Column('date_validation', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'products', ['bar_code'])
    op.create_unique_constraint(None, 'products', ['section'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'date_validation')
    op.drop_column('products', 'section')
    op.drop_column('products', 'bar_code')
    # ### end Alembic commands ###
