"""Adicionar numero ao endereço

Revision ID: 8e0dfbedff93
Revises: 5b3d12d232d1
Create Date: 2025-05-23 21:46:30.750083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0dfbedff93'
down_revision: Union[str, None] = '5b3d12d232d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'number')
    # ### end Alembic commands ###
