"""add cpf to customer

Revision ID: a29912690bbf
Revises: e9e7081a18aa
Create Date: 2025-05-23 04:14:14.786077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29912690bbf'
down_revision: Union[str, None] = 'e9e7081a18aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('cpf', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'cpf')
    # ### end Alembic commands ###
